# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  heroku_user_deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.M3NTORSHIP_DOCKER_USER }}
          password: ${{ secrets.M3NTORSHIP_DOCKER_PASSWORD }}
          registry: docker.m3ntorship.net
          repository: actions-playground
          tags: latest
      
      # install kubectl
      - uses: azure/setup-kubectl@v1
      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin/
          echo "works" | mo
      - name: generate k8s resources from templates
        run: |
          mkdir -p ./deploy/resources
          for f in ./deploy/apply/*.yaml; do mo -s=delivery "$f" > ./deploy/resources/"$(basename $f)"; done
      # Kubectl configuration
      - name: Kubectl configuration
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d -i > ~/.kube/config
          kubectl version
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods
          kubectl apply -f ./deploy/resources