
name: nile
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v1
      # dynamic deployment envs
      - name: set templating envs
        id: version
        run: |
          echo ::set-output name=version::$(git rev-parse --short=4 ${{ github.sha }})
  nile_job:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat $GITHUB_EVENT_PATH
      - run: echo ${github.event.number}-${github.event.pull_request.commits}-${needs.prepare.outputs.version}

      