name: ahmed
on:
  push:
    branches:
      - delete-docker-tags
jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn --cwd .github/custom_actions/delete_old_docker_tags
      - name: Hello world action step
        uses: ./.github/custom_actions/delete_old_docker_tags # Uses an action in the root directory
        id: delete_old_tags
        env:
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
        with:
          keep-last: 50
          user: "m3ntorship"
          repos: '["m3ntorshipcom-storybook"]'
