# This is a basic workflow to help you get started with Actions

name: temp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches-ignore:
      - '**'

env:
  AHMED: true
  M3NTORSHIP_NAME: 'AYOUB'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  temp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: get shortsha
        id: vars
        run: |
         echo ::set-env name=M3NTORSHIP_VERSION::$(git rev-parse --short=4 ${{ github.sha }})
      - name: show envs
        run: |
          env
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo $M3NTORSHIP_VERSION
          echo $M3NTORSHIP_NAME
      - name: another action
        run: echo $M3NTORSHIP_VERSION
      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin/
          echo "works" | mo
          echo 'hello {{{M3NTORSHIP_VERSION}}} and {{{M3NTORSHIP_NAME}}}' | mo